[tool.briefcase]
project_name = "VoiceRecognizer"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/voicerecognizer"
license = "BSD license"
author = 'FIT'
author_email = "fit@example.com"

[tool.briefcase.app.voicerecognizer]
formal_name = "VoiceRecognizer"
description = "App for dictor's voice recognize"
icon = "src/voicerecognizer/resources/voicerecognizer"
sources = ['src/voicerecognizer']
requires = [
]


[tool.briefcase.app.voicerecognizer.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.voicerecognizer.linux]
requires = [
    'toga-gtk>=0.3.0.dev32',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.voicerecognizer.windows]
requires = [
    'toga-winforms>=0.3.0.dev32',
]

# Mobile deployments
[tool.briefcase.app.voicerecognizer.iOS]
requires = [
    'toga-iOS>=0.3.0.dev32',
    'std-nslog==1.0.0'
]

[tool.briefcase.app.voicerecognizer.android]
requires = [
    'toga-android>=0.3.0.dev32'
]
